### ISSUE TITLE
Why don't authors use popular libraries like Llamaindex, Langchain?

### ISSUE THREAD

**Issue by NguyenDinhTiem** [PacktPublishing/LLM-Engineers-Handbook#18]
Hello,  

I've read the first few chapters of the book and paused at the data processing section because I was curious why the author chose not to use libraries like LlamaIndex or LangChain.  

I'm asking because these libraries seem to offer many tools that are similar to the modules the author explains how to build.

Thanks!

**Comment by iusztinpaul** [comment]
Hello,

The book's scope is to teach you how to build these components and how they work under the hood, not to provide you with one-liners that only scratch the surface.
