### ISSUE TITLE
AWS for Digital Twin

### ISSUE THREAD

**Issue by Mimran-colab** [PacktPublishing/LLM-Engineers-Handbook#23]
Hello Dear Authors, 
Can the digital twin based your book be completed without AWS (to avoid any AWS cost) please? Local GPU and memory to be used? Will appreciate any info. Sincerely MI.

**Comment by iusztinpaul** [comment]
Hello @Mimran-colab ,

Without the deployment part, yes, you could run everything on your local GPU (if it has over 16GB VRAM) or just do inference with ~8 GB VRAM while using our pre-trained model available on Hugging Face
