### ISSUE TITLE
pyproject.toml changed significantly since poetry.lock was last generated. Run `poetry lock [--no-update]` to fix the lock file.

### ISSUE THREAD

**Issue by opendeluxe** [PacktPublishing/LLM-Engineers-Handbook#8]
`git clone ...`
`cd ...`

`poetry install --without aws`

Output:

> Installing dependencies from lock file
> 
> pyproject.toml changed significantly since poetry.lock was last generated. Run `poetry lock [--no-update]` to fix the lock file.

**Comment by iusztinpaul** [comment]
Fixed. Thanks for the heads up.
